services:
  maxlab:
    image: navigatorbbs/maxlab:latest
    container_name: maxlab
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ${NOTEBOOK_PATH:-/mnt/storage/maxlab}:/home/jovyan/work
    environment:
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
